version: '0.1.1'

services:
  app:
    build: .
    container_name: ${PROJECT_NAME}
    volumes:
      - ./src:/app
    environment:
      - FLET_SERVER_PORT=8550
    ports:
      - 15${PROJECT_ID}:8550 #port for jdeapp

networks:
  default:
    name: ${PROJECT_NAME}_network